name: Hourly Data Scrape

on:
  schedule:
    # Runs at the top of every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main

# ADD THIS PERMISSIONS BLOCK
permissions:
  contents: write # Allows the action to write to your repository

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the scraper script
        run: python scraper.py

      - name: Commit and push if there are changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated: Updated ER capacity data"
          file_pattern: "index.html"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"
